data<-read.xlsx(file.choose())
dim(data)
print(data)
#a<-arrange(data,First.name)
#a<-data %>% arrange(desc(First.name))
#print(a)
print(data%>%arrange(First.name))
print(data%>%arrange(desc(First.name)))
print(data %>% filter(First.name == "Abbot") %>% select(Email))
print(data %>% filter(Gender == "Male") %>% count(Gender))
print(data %>% filter(Gender == "Female") %>% count(Gender))

