empID<-c(1,2,3,4)
empName<-c("A","B","C","D")
empSal<-c(10000,20000,25000,30000)
employee<-list("ID"=empID,"Name"=empName,"salary"=empSal)
print(employee)
print(employee $Name)
empAge<-c(21,34,56,24)
empAge<-list("Age"=empAge)
employee<-c(employee,empAge)
print(employee)
m<-matrix (unlist(employee), nrow=4,ncol=4,byrow=FALSE)
print(m)
print(class(m))
