employee<-read.csv(file.choose())
print(employee)
print(nrow(employee))
print(nrow(employee$sal))
e<-subset(employee,Department=="IT")                         
print(e)
f<-subset(employee,Department=="IT"&Sal>10000)
print(f)
g<-max(employee["Sal"])
h<-subset(employee,Sal==g)
print(h)
employee<-write.csv(c(1,"Shubhrangshu",25000),"C:\\Users\\USER\\OneDrive\\Desktop\\R lab\\data-data.csv")
print(employee)
employee<-read.csv("C:\\Users\\USER\\OneDrive\\Desktop\\R lab\\data-data.csv")
print(employee)

